## This Toolkit aims to implement the basic image processing tools and libraries. This exercise will serve as an understing to the operations implemented in the Streamlit GUI using basic maths and visualization (Open CV and othe high level packages are not used here)

### Let's first import basic image processing or related libraries

In [1]:
from PIL import Image
import matplotlib.pyplot as plt
%matplotlib widget
import numpy as np

### First load an image and visualize it

In [2]:
image = plt.imread("Lenna.png")
plt.imshow(image)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Finding dimensions of the image

In [3]:
height, width, channels = image.shape
print(f"Image Dimensions: {width} x {height}")
print(f"Channels: {channels}")

Image Dimensions: 512 x 512
Channels: 3


### An RGB image can be decomposed into three channels, Red(R), Green(G), Blue(B). In this subsection, let's visualize each channel separately

In [4]:
def VisualizeChannel(image,channel):
    '''
    This function is helpful to visualize a specific channel of an RGB image.
    image: RGB image
    channel: channel, one wish to visualize (can take value 0 (for red), 1(green), 2(blue))
    '''
    %matplotlib widget
    #write your code here
    
    # Initialize an array of zeros with the same shape as the original image
    channel_image = np.zeros_like(image)
    
    # Set the selected channel to the original image's channel values
    channel_image[..., channel] = image[..., channel]
    
    # Get the min and max intensity values for the channel
    min_intensity = np.min(channel_image)
    max_intensity = np.max(channel_image)
    #print(f"Channel {['Red', 'Green', 'Blue'][channel]} - Min Intensity: {min_intensity}, Max Intensity: {max_intensity}")
    
    plt.imshow(channel_image)
    plt.title(f'Channel {["Red", "Green", "Blue"][channel]}')
    plt.axis('off')  # Hide axis
    plt.show()
    
    
    return channel_image    # 'output' is image's particular channel values

In [5]:
# Visualizing red channel
VisualizeChannel(image, 0)  # Red channel

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([[[0.8862745 , 0.        , 0.        ],
        [0.8862745 , 0.        , 0.        ],
        [0.8745098 , 0.        , 0.        ],
        ...,
        [0.9019608 , 0.        , 0.        ],
        [0.8666667 , 0.        , 0.        ],
        [0.78431374, 0.        , 0.        ]],

       [[0.8862745 , 0.        , 0.        ],
        [0.8862745 , 0.        , 0.        ],
        [0.8745098 , 0.        , 0.        ],
        ...,
        [0.9019608 , 0.        , 0.        ],
        [0.8666667 , 0.        , 0.        ],
        [0.78431374, 0.        , 0.        ]],

       [[0.8862745 , 0.        , 0.        ],
        [0.8862745 , 0.        , 0.        ],
        [0.8745098 , 0.        , 0.        ],
        ...,
        [0.9019608 , 0.        , 0.        ],
        [0.8666667 , 0.        , 0.        ],
        [0.78431374, 0.        , 0.        ]],

       ...,

       [[0.32941177, 0.        , 0.        ],
        [0.32941177, 0.        , 0.        ],
        [0.36078432, 0

In [6]:
VisualizeChannel(image, 1)  # Green channel

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([[[0.        , 0.5372549 , 0.        ],
        [0.        , 0.5372549 , 0.        ],
        [0.        , 0.5372549 , 0.        ],
        ...,
        [0.        , 0.5803922 , 0.        ],
        [0.        , 0.50980395, 0.        ],
        [0.        , 0.3882353 , 0.        ]],

       [[0.        , 0.5372549 , 0.        ],
        [0.        , 0.5372549 , 0.        ],
        [0.        , 0.5372549 , 0.        ],
        ...,
        [0.        , 0.5803922 , 0.        ],
        [0.        , 0.50980395, 0.        ],
        [0.        , 0.3882353 , 0.        ]],

       [[0.        , 0.5372549 , 0.        ],
        [0.        , 0.5372549 , 0.        ],
        [0.        , 0.5372549 , 0.        ],
        ...,
        [0.        , 0.5803922 , 0.        ],
        [0.        , 0.50980395, 0.        ],
        [0.        , 0.3882353 , 0.        ]],

       ...,

       [[0.        , 0.07058824, 0.        ],
        [0.        , 0.07058824, 0.        ],
        [0.        , 0

In [7]:
VisualizeChannel(image, 2)  # Blue channel

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([[[0.        , 0.        , 0.49019608],
        [0.        , 0.        , 0.49019608],
        [0.        , 0.        , 0.52156866],
        ...,
        [0.        , 0.        , 0.47843137],
        [0.        , 0.        , 0.43137255],
        [0.        , 0.        , 0.3529412 ]],

       [[0.        , 0.        , 0.49019608],
        [0.        , 0.        , 0.49019608],
        [0.        , 0.        , 0.52156866],
        ...,
        [0.        , 0.        , 0.47843137],
        [0.        , 0.        , 0.43137255],
        [0.        , 0.        , 0.3529412 ]],

       [[0.        , 0.        , 0.49019608],
        [0.        , 0.        , 0.49019608],
        [0.        , 0.        , 0.52156866],
        ...,
        [0.        , 0.        , 0.47843137],
        [0.        , 0.        , 0.43137255],
        [0.        , 0.        , 0.3529412 ]],

       ...,

       [[0.        , 0.        , 0.23529412],
        [0.        , 0.        , 0.23529412],
        [0.        , 0

### Intensity Manipulation: RGB to Gray

In [8]:
# Visualizing the image
%matplotlib widget
image2 = plt.imread('rgb.jpg')
plt.imshow(image2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
def RGB2Gray(image): 
    '''
    This function converts an RGB image to grayscale
    image: RGB image
    '''
    %matplotlib widget
    #write you code here and visualize the result
    gray = 0.3 * image[..., 0] + 0.59 * image[..., 1] + 0.11 * image[..., 2]
    
    plt.imshow(gray, cmap='gray')
    plt.title("Grayscale Image")
    plt.axis('off')  # Hide axis
    plt.show()
    
    return gray       #'gray' is grayscale image, converted from RGB image

In [10]:
#RGB to Gray Scale results
gray_image = RGB2Gray(image2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

We can also convert a gray image to a binary image.

$$
I(x, y) = 
\begin{cases} 
1 & \text{if } I(x, y) \geq T \\
0 & \text{if } I(x, y) < T & \text{where T is threshold}
\end{cases}
$$

Though there are proper methods (such as the Otsu method) to find a suitable $T$, we will not go into details of those algorithms and randomly select T values and visualize the result.

In [11]:
# The threshold T is typically chosen from the range 0 to 255, which corresponds to the possible intensity values of an 
# 8-bit grayscale image.

def Gray2Binary(image,T):
    '''
    This function converts a gray image to binary based on the rule stated above.
    image: image (can be RGB or gray); if the image is RGB, convert it to gray first
    T: Threshold
    '''

    #check if image is RGB if yes, convert it to gray
    flag = len(image.shape)
    if flag == 3:        #i.e. RGB image, hence to be converted to gray
        # write code to convert it to gray or you can call function "RGB2Gray" defined in task2.1
        gray_image = RGB2Gray(image)

    #Write code to threshold image based on the rule stated above and return this binarized image (say it 'bimage')
    bimage = np.where(gray_image >= T, 1, 0)


    #write code to visualize the resultant image
    plt.imshow(bimage, cmap='gray')
    plt.title(f'Binary Image with T = {T}')
    plt.axis('off')  # Hide axis
    plt.show()


    return bimage

In [12]:
#Grayscale to binary
image3 = plt.imread('rgb.jpg')  # Replace with your image path
T = 127  # Set the threshold value
bimg = Gray2Binary(image3, T)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Intensity Manipulation: Uniform Brightness Scaling

Image is a matrix. 

Hence we can perform multiplication/division or addition/subtraction operations.

These operations will change the brightness value of the image; can make an image brighter or darker depending on the multiplying/scaling factor. 

For this task, We'll change the image brightness uniformly. Consider scale to be 0.3,0.5,1,2 for four different cases.

In [13]:
def UniformBrightScaling(image,scale):
    '''
    This function uniformly increases or decreases the pixel values (of all image locations) by a factor 'scale'.
    image: image (can be RGB or gray image)
    scale: A scalar by which pixels'svalues need to be multiplied
    '''
    #write your code here
    if len(image.shape) == 3:  # RGB image
        gray_image = RGB2Gray(image)
    else:
        gray_image = image  # It's already a grayscale image
        
    # Apply the scaling factor to all pixel values
    output = gray_image * scale
    # Clip the output to ensure pixel values stay within the valid range [0, 1]
    output = np.clip(output, 0, 1)

    #display the resultant image
    plt.imshow(output, cmap='gray')
    plt.title(f'Brightness Scaled by {scale}')
    plt.axis('off')
    plt.show()

    return output        #replace output with the variable name you used for final result

In [14]:
UniformBrightScaling(image, 1)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([[0.6367843 , 0.6367843 , 0.6367059 , ..., 0.66564703, 0.6082353 ,
        0.5031765 ],
       [0.6367843 , 0.6367843 , 0.6367059 , ..., 0.66564703, 0.6082353 ,
        0.5031765 ],
       [0.6367843 , 0.6367843 , 0.6367059 , ..., 0.66564703, 0.6082353 ,
        0.5031765 ],
       ...,
       [0.16635294, 0.16635294, 0.1957255 , ..., 0.4086667 , 0.3924706 ,
        0.38576472],
       [0.1719608 , 0.1719608 , 0.21372549, ..., 0.40662748, 0.41215685,
        0.42380393],
       [0.1719608 , 0.1719608 , 0.21372549, ..., 0.40662748, 0.41215685,
        0.42380393]], dtype=float32)

In [15]:
UniformBrightScaling(image, 2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.3327059 , 0.3327059 , 0.391451  , ..., 0.8173334 , 0.7849412 ,
        0.77152944],
       [0.3439216 , 0.3439216 , 0.42745098, ..., 0.81325495, 0.8243137 ,
        0.84760785],
       [0.3439216 , 0.3439216 , 0.42745098, ..., 0.81325495, 0.8243137 ,
        0.84760785]], dtype=float32)

### Image Filtering

In this section we'll be performing some of the image filtering techniques.

Convolution is one of the most widely used operations for images.

Convolution can be used as a feature extractor; different kernel results in various types of features.

#### Sobel Filter and Gaussian Filter implementation

In [16]:
def feature_extractor(image,kernel):
    '''
    This function performs convolution operation to a gray image. We will consider 3*3 kernel here.
    In general kernel can have shape (2n+1) * (2n+1)  where n>= 0
    image: image (can be RGB or gray); if RGB convert it to gray
    kernel: 3*3 convolution kernel
    '''
    # first convert RGB to gray if input is RGB image

    l = len(image.shape)

    if l == 3:
        #write code to convert it to gray scale
        image = RGB2Gray(image)

    # write code to create a zero array of size (r,c) which will store the resultant value at specific pixel locations (say it output)
    r, c = image.shape
    output = np.zeros((r, c))


    #write code to create a zero array with size (r+2,c+2) if (r,c) is the gray image size.  (say it pad_img)
    pad_img = np.pad(image, ((1, 1), (1, 1)), mode='constant', constant_values=0)

    #write code to convolve the image        
    for row in range(1, r + 1):
        for col in range(1, c + 1):
            # Select 3x3 patch with the center at (row, col)
            patch = pad_img[row-1:row+2, col-1:col+2]

            # Perform element-wise multiplication between the patch and the kernel, then sum the result
            output[row-1, col-1] = np.sum(patch * kernel)

    return output

sobel_kernel = np.array([[1, 0, -1],
                         [1, 0, -1],
                         [0, 0, 0]])

sobel_kernel2 = np.array([[1, 2, 1],
                         [0, 0, 0],
                         [-1, -2, -1]])

gaussian_kernel = np.array([[1, 2, 1],
                            [2, 4, 2],
                            [1, 2, 1]]) / 16


In [17]:
#Sobel Filter results
filtered_image = feature_extractor(image, sobel_kernel)
plt.imshow(filtered_image, cmap='gray')
plt.title("Filtered Image")
plt.axis('off')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [18]:
#Gaussian Filter results
filtered_image = feature_extractor(image, gaussian_kernel)
plt.imshow(filtered_image, cmap='gray')
plt.title("Filtered Image")
plt.axis('off')
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Transformation: Rotation

In [19]:
def rotate_image(image, angle):
    %matplotlib widget
    """
    Rotate an image by a given angle (in degrees) using only numpy and matplotlib.
    
    Parameters:
        image : numpy.ndarray
            Input image (RGB or grayscale).
        angle : float
            Angle in degrees. Positive = counter-clockwise, Negative = clockwise.
    
    Returns:
        rotated : numpy.ndarray
            Rotated image.
    """
    # Convert angle to radians
    theta = np.deg2rad(angle)
    
    # Rotation matrix
    rotation_matrix = np.array([
        [np.cos(theta), -np.sin(theta)],
        [np.sin(theta),  np.cos(theta)]
    ])
    
    # Image dimensions
    h, w = image.shape[:2]
    
    # Coordinates of corners
    corners = np.array([
        [-w/2, -h/2],
        [ w/2, -h/2],
        [ w/2,  h/2],
        [-w/2,  h/2]
    ])
    
    # Rotate corners to find new image bounds
    new_corners = np.dot(corners, rotation_matrix.T)
    min_x, min_y = new_corners.min(axis=0)
    max_x, max_y = new_corners.max(axis=0)
    
    new_w = int(np.ceil(max_x - min_x))
    new_h = int(np.ceil(max_y - min_y))
    
    # Create grid for new image
    y_idx, x_idx = np.indices((new_h, new_w))
    x_coords = x_idx - new_w/2
    y_coords = y_idx - new_h/2
    
    coords = np.stack([x_coords.ravel(), y_coords.ravel()], axis=1)
    
    # Apply inverse rotation
    inv_rotation = np.linalg.inv(rotation_matrix)
    original_coords = np.dot(coords, inv_rotation.T)
    
    orig_x = (original_coords[:,0] + w/2).reshape((new_h, new_w))
    orig_y = (original_coords[:,1] + h/2).reshape((new_h, new_w))
    
    # Initialize rotated image
    if image.ndim == 3:
        rotated = np.zeros((new_h, new_w, image.shape[2]), dtype=image.dtype)
    else:
        rotated = np.zeros((new_h, new_w), dtype=image.dtype)
    
    # Nearest neighbor interpolation
    orig_x_round = np.round(orig_x).astype(int)
    orig_y_round = np.round(orig_y).astype(int)
    
    valid_mask = (
        (orig_x_round >= 0) & (orig_x_round < w) &
        (orig_y_round >= 0) & (orig_y_round < h)
    )
    
    if image.ndim == 3:
        rotated[valid_mask] = image[orig_y_round[valid_mask], orig_x_round[valid_mask], :]
    else:
        rotated[valid_mask] = image[orig_y_round[valid_mask], orig_x_round[valid_mask]]
    
    # Show rotated image
    plt.imshow(rotated, cmap="gray" if image.ndim==2 else None)
    plt.title(f"Rotated by {angle}°")
    plt.axis("off")
    plt.show()
    
    return rotated


In [20]:
#Rotation results
rotate_image(image, 9)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

### Edge Detection

Canny Edge Detection

In [21]:
def gaussian_kernel(size=5, sigma=1.0):
    """Generate a Gaussian kernel."""
    ax = np.linspace(-(size//2), size//2, size)
    xx, yy = np.meshgrid(ax, ax)
    kernel = np.exp(-(xx**2 + yy**2) / (2 * sigma**2))
    return kernel / np.sum(kernel)

def convolve(image, kernel):
    """Convolve 2D kernel over a grayscale image."""
    h, w = image.shape
    kh, kw = kernel.shape
    pad_h, pad_w = kh//2, kw//2
    padded = np.pad(image, ((pad_h,pad_h),(pad_w,pad_w)), mode='edge')
    result = np.zeros_like(image, dtype=np.float64)
    for i in range(h):
        for j in range(w):
            region = padded[i:i+kh, j:j+kw]
            result[i,j] = np.sum(region * kernel)
    return result

def sobel_filters(img):
    """Compute gradients using Sobel filters."""
    Kx = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
    Ky = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])
    Gx = convolve(img, Kx)
    Gy = convolve(img, Ky)
    magnitude = np.hypot(Gx, Gy)
    magnitude = magnitude / magnitude.max() * 255
    direction = np.arctan2(Gy, Gx)
    return magnitude, direction

def non_maximum_suppression(mag, dir):
    """Thin edges using non-maximum suppression."""
    H, W = mag.shape
    Z = np.zeros((H,W), dtype=np.float64)
    angle = dir * 180. / np.pi
    angle[angle < 0] += 180

    for i in range(1,H-1):
        for j in range(1,W-1):
            q = 255
            r = 255
            # Check neighbours in the gradient direction
            if (0 <= angle[i,j] < 22.5) or (157.5 <= angle[i,j] <= 180):
                q = mag[i, j+1]
                r = mag[i, j-1]
            elif (22.5 <= angle[i,j] < 67.5):
                q = mag[i+1, j-1]
                r = mag[i-1, j+1]
            elif (67.5 <= angle[i,j] < 112.5):
                q = mag[i+1, j]
                r = mag[i-1, j]
            elif (112.5 <= angle[i,j] < 157.5):
                q = mag[i-1, j-1]
                r = mag[i+1, j+1]

            if (mag[i,j] >= q) and (mag[i,j] >= r):
                Z[i,j] = mag[i,j]
            else:
                Z[i,j] = 0
    return Z

def threshold(img, low_ratio=0.05, high_ratio=0.15):
    """Double thresholding."""
    high = img.max() * high_ratio
    low = high * low_ratio
    
    strong = 255
    weak = 75
    
    res = np.zeros_like(img, dtype=np.uint8)
    strong_i, strong_j = np.where(img >= high)
    weak_i, weak_j = np.where((img <= high) & (img >= low))
    
    res[strong_i, strong_j] = strong
    res[weak_i, weak_j] = weak
    
    return res, weak, strong

def hysteresis(img, weak=75, strong=255):
    """Edge tracking by hysteresis."""
    H, W = img.shape
    for i in range(1, H-1):
        for j in range(1, W-1):
            if img[i,j] == weak:
                if np.any(img[i-1:i+2, j-1:j+2] == strong):
                    img[i,j] = strong
                else:
                    img[i,j] = 0
    return img

def canny_edge(image, sigma=1.0, low_ratio=0.05, high_ratio=0.15):
    %matplotlib widget
    """Canny Edge Detection (NumPy + Matplotlib)."""
    # Ensure grayscale
    if image.ndim == 3:
        image = np.dot(image[...,:3], [0.299, 0.587, 0.114])
    
    # Step 1: Gaussian smoothing
    kernel = gaussian_kernel(size=5, sigma=sigma)
    smoothed = convolve(image, kernel)
    
    # Step 2: Gradients
    mag, direction = sobel_filters(smoothed)
    
    # Step 3: Non-maximum suppression
    nms = non_maximum_suppression(mag, direction)
    
    # Step 4: Double thresholding
    thresh, weak, strong = threshold(nms, low_ratio, high_ratio)
    
    # Step 5: Hysteresis
    edges = hysteresis(thresh, weak, strong)
    
    return edges

In [23]:
edges = canny_edge(image, sigma=1.4, low_ratio=0.05, high_ratio=0.15)

plt.figure(figsize=(12,6))
plt.subplot(1,2,1)
plt.imshow(image, cmap='gray' if image.ndim==2 else None)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(edges, cmap='gray')
plt.title("Canny Edges")
plt.axis("off")
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …